# Generated by Django 5.2.7 on 2025-11-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0003_alter_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
