# Generated by Django 5.2.7 on 2025-11-10 19:53

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_orders', '0005_contact_avatar_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='avatar',
        ),
        migrations.AddField(
            model_name='order',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
